smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -165,9 +165,9 @@ jobs:
             --output text >> .circleci/ansible/inventory.txt
 
       - persist_to_workspace:
-          root: .
+          root: ~/
           paths:
-            - .circleci/ansible/inventory.txt
+            - project/.circleci/ansible/inventory.txt
 
       - destroy-environment
 
@@ -281,6 +281,49 @@ jobs:
             ansible-playbook -i inventory.txt deploy-backend.yml
       - destroy-environment
       - revert-migrations
+
+  smoke-test:
+    docker:
+      - image: python:3.10.5-alpine3.16
+    steps:
+      - checkout
+      - run:
+          name: Install Dependencies
+          command: |
+            apk add --update curl aws-cli nodejs npm
+            apk add --update npm
+      - run:
+          name: Backend Smoke Test
+          command: |
+            BACKEND_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+            export API_URL=http://${BACKEND_IP}:3030
+            if curl -s $API_URL/api/status | grep "ok"
+            then
+              echo "SUCCESS, Backend Deployed!!"
+              exit 0
+            else
+              echo "FAILED, Something went Wrong!!"
+              exit 1
+            fi
+      - run:
+          name: Frontend Smoke Test
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-west-2.amazonaws.com/#/employees"            
+            echo ${URL}
+            if curl -s ${URL} | grep "Welcome"
+            then
+              # Change this to 0 after the job fails
+              echo "SUCCESS, Backend Deployed!!"
+              return 1
+            else
+              echo "FAILED, Something went Wrong!!"
+              return 1
+            fi
+      - destroy-environment
+      - revert-migrations
 workflows:
   default:
     jobs:
@@ -307,3 +350,5 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
